
package br.client;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExameService", targetNamespace = "http://service.exame.socproject.orion.com.br/", wsdlLocation = "META-INF/wsdl/ExameService.wsdl")
public class ExameService
    extends Service
{

    private final static URL EXAMESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXAMESERVICE_EXCEPTION;
    private final static QName EXAMESERVICE_QNAME = new QName("http://service.exame.socproject.orion.com.br/", "ExameService");

    static {
        EXAMESERVICE_WSDL_LOCATION = br.client.ExameService.class.getClassLoader().getResource("META-INF/wsdl/ExameService.wsdl");
        WebServiceException e = null;
        if (EXAMESERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/ExameService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        EXAMESERVICE_EXCEPTION = e;
    }

    public ExameService() {
        super(__getWsdlLocation(), EXAMESERVICE_QNAME);
    }

    public ExameService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMESERVICE_QNAME, features);
    }

    public ExameService(URL wsdlLocation) {
        super(wsdlLocation, EXAMESERVICE_QNAME);
    }

    public ExameService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMESERVICE_QNAME, features);
    }

    public ExameService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExameService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IExameService
     */
    @WebEndpoint(name = "ExameServicePort")
    public IExameService getExameServicePort() {
        return super.getPort(new QName("http://service.exame.socproject.orion.com.br/", "ExameServicePort"), IExameService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IExameService
     */
    @WebEndpoint(name = "ExameServicePort")
    public IExameService getExameServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.exame.socproject.orion.com.br/", "ExameServicePort"), IExameService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMESERVICE_EXCEPTION!= null) {
            throw EXAMESERVICE_EXCEPTION;
        }
        return EXAMESERVICE_WSDL_LOCATION;
    }

}
