
package br.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IExameService", targetNamespace = "http://service.exame.socproject.orion.com.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IExameService {


    /**
     * 
     * @param mensagemRequisicao
     * @return
     *     returns br.client.MensagemRespostaNode
     */
    @WebMethod
    @WebResult(partName = "return")
    public MensagemRespostaNode mensagemRequisicao(
        @WebParam(name = "mensagemRequisicao", partName = "mensagemRequisicao")
        MensagemRequisicaoNode mensagemRequisicao);

    /**
     * 
     * @param str
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String hello(
        @WebParam(name = "str", partName = "str")
        String str);

}
